name: IBM watsonx.ai - Text Summarization
description: |
  This AMP demonstrates how to use watson machine learning Python SDK to call watsonx.ai models from CML workspace. In this AMP, text summarization based on custom instruction is used as an example but these foundation models are capable of much more such as question-answering, classification, extraction and so on.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-12-01"

environment_variables:
  IBM_WATSONXAI_ENDPOINT:
    default: "ibm_watsonxai_endpoint"
    description: >-
      IBM watsonx.ai Endpoint
  IBM_API_KEY:
    default: "ibm_api_key"
    description: >-
      IBM API Key
  IBM_PROJECT_ID:
    default: "ibm_project_id"
    description: >-
      IBM Project ID

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: deps/setup.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  - type: start_application
    name: IBM watsonx.ai - Text Summarization
    subdomain: cml-task
    script: app/watsonx_app.py
    long_summary: Launching Application.
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
