name: IBM watsonx.ai - Text Summarization using Granite model
description: |
  This AMP demonstrates an application which uses IBM watsonx.ai model for LLM inference with a summarization usecase.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2023-12-01"

environment_variables:
  IBM_WATSONXAI_ENDPOINT:
    default: "ibm_watsonxai_endpoint"
    description: >-
      IBM watsonx.ai Endpoint
  IBM_API_KEY:
    default: "ibm_api_key"
    description: >-
      IBM API Key
  IBM_PROJECT_ID:
    default: "ibm_project_id"
    description: >-
      IBM Project ID

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.9
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: deps/setup.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 4

  - type: start_application
    name: IBM watsonx.ai - Text Summarization using Granite model
    subdomain: cml-task
    script: app/watsonx_app.py
    long_summary: Launching Application.
    cpu: 2
    memory: 8
    environment_variables:
      TASK_TYPE: START_APPLICATION
